<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'InoxNavigation\Navigation\Service\CustomNavigationFactory' => __DIR__ . '/src/Navigation/Service/CustomNavigationFactory.php',
    'InoxNavigation\Module'                                     => __DIR__ . '/Module.php',
);